[mgr]
ratio = [1, 2, 0]
sort_by = "natural"
sort_dir_first = true
show_hidden = false

[preview]
enabled = false

[opener]
edit = [
    { run = 'zellij action edit -d Right "$@"', block = false, for = "unix" },
]
preview = [
    { run = 'zellij run -c -d Right -- bat --paging=always --style=numbers --color=always "$@"', block = false, for = "unix" },
]
open = [
    { run = 'open "$@"', for = "macos" },
    { run = 'xdg-open "$@"', for = "linux" },
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "application/json", use = "edit" },
    { mime = "application/xml", use = "edit" },
    { mime = "application/javascript", use = "edit" },
    { mime = "application/typescript", use = "edit" },
    { mime = "application/x-shellscript", use = "edit" },
    { mime = "application/toml", use = "edit" },
    { mime = "application/yaml", use = "edit" },
    { mime = "*", use = "open" },
]
